export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const ADD_SHOP_BEGIN = 'ADD_SHOP_BEGIN'
export const ADD_SHOP_SUCCESS = 'ADD_SHOP_SUCCESS'
export const ADD_SHOP_ERROR = 'ADD_SHOP_ERROR'

export const GET_SHOP_BEGIN = "GET_SHOP_BEGIN"
export const GET_SHOP_SUCCESS = "GET_SHOP_SUCCESS"
export const GET_SHOP_ERROR = "GET_SHOP_ERROR"

export const ADD_TAG_BEGIN = "ADD_TAG_BEGIN"
export const ADD_TAG_SUCCESS = "ADD_TAG_SUCCESS"
export const ADD_TAG_ERROR = "ADD_TAG_ERROR"

export const DELETE_TAG_BEGIN = "DELETE_TAG_BEGIN"
export const DELETE_TAG_SUCCESS = "DELETE_TAG_SUCCESS"
export const DELETE_TAG_ERROR = "DELETE_TAG_ERROR"

export const GET_SHOP_CITY_BEGIN = "GET_SHOP_CITY_BEGIN"
export const GET_SHOP_CITY_SUCCESS = "GET_SHOP_CITY_SUCCESS"
export const GET_SHOP_CITY_ERROR = "GET_SHOP_CITY_ERROR"

export const HANDLE_CHANGE = "HANDLE_CHANGE"